export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const MOVE_TASK_TO_IN_PROGRESS = "MOVE_TASK_TO_IN_PROGRESS";
export const MOVE_TASK_IN_TO_DO = "MOVE_TASK_IN_TO_DO";
export const MOVE_TASK_TO_DONE = "MOVE_TASK_TO_DONE";
export const MOVE_TASK_TO_IN_PROGRESS_FROM_DONE =
  "MOVE_TASK_TO_IN_PROGRESS_FROM_DONE";
export const DELETE_TASK_FROM_DONE = "DELETE_TASK_FROM_DONE";
export const SET_APP_DATA = "SET_APP_DATA";
