export enum ActionTypes {
  SET_APP_DATA = "SET_APP_DATA",
  SET_ERROR_ACTION = "SET_ERROR_ACTION",
  SET_AUTORIZATION_STATUS = "SET_AUTORIZATION_STATUS",
  SET_TASK_TO_DELETE = "SET_TASK_TO_DELETE",
  RESET_TASK_TO_DELETE = "RESET_TASK_TO_DELETE",
}
